# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character] # The name of the module we are configuring is "character"
success_symbol = "[ï‘„](bold fg:#0AFF9D)" # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[ï‘„](bold fg:#FE5F55)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
min_time = 20000

[git_branch] 
symbol = "îœ¥"
format = "[$symbol $branch](bold fg:#DEFFF2) "

[directory]
format = "in [$path](bold) "
truncation_length = 1
home_symbol = "ğŸ "

[username]
show_always = true
format = "[$user](bold) "

[java]
style = "bold red"

[container]
disabled = true
symbol = "ğŸ“¦"
format = '[$symbol]($style) '

[env_var.MAVEN_LOCAL_SETTINGS]
symbol = 'â—‰'
format ="[$symbol]($style) "
style = "yellow"
